export const STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  FORBIDDEN: 403,
  BAD_REQUEST: 400,
  CONFLICT: 409,
  SERVER_ERROR: 500,
};

export const SYMBOLS = {
  PLAYER: 'X',
  COMPUTER: 'O',
  EMPTY: '',
};

export const GAME_STATE = {
  INCOMPLETE: 0,
  COMPUTER_WON: SYMBOLS.COMPUTER,
  PLAYER_WON: SYMBOLS.PLAYER,
  TIE: 'GAME_DRAW'
};

export const GAME_BOARD_LENGTH = 9;

